#!/bin/sh
set -eu

# https://github.com/skarnet/s6/releases
S6_VERSION="2.9.1.0"
# https://github.com/skarnet/s6/blob/v2.9.1.0/doc/upgrade.html
SKALIBS_VERSION="2.9.1.0"
EXECLINE_VERSION="2.6.0.0"

CONFIGURE_OPTS="--prefix=/usr --libdir=/usr/lib --enable-static --disable-shared"

# Folder used for libs installation so linking is easier to specify later.
# We use static linking so we won't need those libs once the final binaries are produced.
WORK_DIR="$PWD/install"
mkdir -p "${WORK_DIR}"

# Switch working directory.
cd "$(dirname "${0}")"

# Build skalibs.
curl -L "https://github.com/skarnet/skalibs/archive/v${SKALIBS_VERSION}.tar.gz" | tar -xz
cd "skalibs-${SKALIBS_VERSION}"
# shellcheck disable=SC2086
./configure ${CONFIGURE_OPTS} --datadir=/etc
make
make DESTDIR="${WORK_DIR}" install
cd -

# Build execline.
curl -L "https://github.com/skarnet/execline/archive/v${EXECLINE_VERSION}.tar.gz" | tar -xz
cd "execline-${EXECLINE_VERSION}"
# shellcheck disable=SC2086
./configure ${CONFIGURE_OPTS} \
	--with-include="${WORK_DIR}/usr/include" \
	--with-lib="${WORK_DIR}/usr/lib" \
	--with-sysdeps="${WORK_DIR}/usr/lib/skalibs/sysdeps"
make
make DESTDIR="${WORK_DIR}" install
cd -

# Build s6.
curl -L "https://github.com/skarnet/s6/archive/v${S6_VERSION}.tar.gz" | tar -xz
cd "s6-${S6_VERSION}"
# shellcheck disable=SC2086
./configure ${CONFIGURE_OPTS} \
	--with-include="${WORK_DIR}/usr/include" \
	--with-lib="${WORK_DIR}/usr/lib" \
	--with-sysdeps="${WORK_DIR}/usr/lib/skalibs/sysdeps"
make

# Install s6 binaries on the system.
make DESTDIR="${DIST_DIR}" install-bin install-libexec
